#
# Makefile for the rmi4 drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPAD_SYNAPTICS_RMI4_I2C) += rmi_bus.o rmi_dev.o rmi_driver.o rmi_f01.o rmi_f11.o rmi_f19.o rmi_f34.o rmi_f54.o rmi_i2c.o rmi_spi.o
